import AGLoading from "./AGLoading/AGLoading";
import Header from "./Header/Header";
import {
    setAppLang,
    traductor,
    deviceLanguage,
} from "./Traductor";
import {
    LoadingContext,
    LoadingProvider,
    UserContext,
    UserProvider,
    NoUserContext,
    NoUserProvider,
} from "./AGContext";
import {
    InputText,
    InputDynamic,
    InputDropdown,
    KeyboardHeight,
} from "./Inputs";
import {
    delay,
    getCurrentDate,
    goToScreen,
    getDataDoc,
    getDataDocs,
    distanceBetweenPoints,
    arraysAreEqualUsingJSON,
    average,
    InfiniteList,
} from "./AGFunctions";
import {
    primaryColor,
    secondaryColor,
    tertiaryColor,
    boxShadow,
    boxShadowInput,
    bottomTarSpace,
    statusBarHeigth,
    API_KEY,
    days,
    shopTypes,
    campaignTypes,
    getShopTypeLabel,
    shopTypeCategory,
    shopCategoryType,
} from "./AGGlobalVariables";
import {
    StackNavigator,
    TabNavigator,
    DrawerNavigator,
    StackLogin,
    TabLoginNavigator,
} from "./AGNavigator";
export {
    setAppLang,
    traductor,
    AGLoading,
    Header,
    InputText,
    InputDynamic,
    InputDropdown,
    KeyboardHeight,
    delay,
    getCurrentDate,
    goToScreen,
    StackNavigator,
    TabNavigator,
    DrawerNavigator,
    StackLogin,
    TabLoginNavigator,
    LoadingContext,
    LoadingProvider,
    NoUserContext,
    NoUserProvider,
    primaryColor,
    secondaryColor,
    tertiaryColor,
    boxShadow,
    boxShadowInput,
    bottomTarSpace,
    getDataDoc,
    getDataDocs,
    distanceBetweenPoints,
    UserContext,
    UserProvider,
    statusBarHeigth,
    API_KEY,
    days,
    arraysAreEqualUsingJSON,
    deviceLanguage,
    average,
    InfiniteList,
    shopTypes,
    campaignTypes,
    getShopTypeLabel,
    shopTypeCategory,
    shopCategoryType,
}